# pandas 시작하기

- 앞으로 가장 자주 살펴볼 라이브러리다. 고수준의 자료구조와 파이썬에서 빠르고 쉽게 사용할 수 잇는 데이터 분석 도구를 포함하고 있다. 
- pandas는 Numpy와 Scip, 분석 라이브러리인 statsmodels와 scikit-learn, 시각화 도구인 matplotlib과 함께 사용하는 경우가 흔하다. 
- pandas는 for 문을 사용하지 않고 데이터를 처리하거나 배열 기반의 함수를 제공하는 등 Numpy 배열 기반 계산 스타일을 많이 차용했다. 
- pandas는 표 형식의 데이터나 다양한 형태의 데이터를 다루는 데 초점을 맞춰 설계했다. Numpy 는 단일 산술 배열 데이터를 다루는 데 특화되어 있다. 

In [5]:
import pandas as pd

In [9]:
from pandas import Series, DataFrame

### pandas 자료구조 소개
- Series : 일련의 객체를 담을 수 있는 1차원 배열 같은 자료구조다. 그리고 index 라고 하는 배열의 데이터와 연관된 이름을 가지고 있다. 

In [10]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

Series 객체의 문자열 표현은 왼쪽에 색인을 보여주고, 오른쪽에 대항 색인의 값을 보여준다. Series의 배열과 색인 객체는 각각 values와 index 속성을 통해 얻을 수 있다. 

In [12]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [13]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [14]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [15]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [16]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [18]:
obj2['a']

-5

In [19]:
obj2['d']

4

In [20]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [21]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

불리언 배열 : 논리자료형 0,1(False, True)로 이뤄진 배열이다. 

In [22]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [24]:
import numpy as np

In [34]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Series는 색인값에 데이터값을 매핑하고 있으므로 파이썬의 사전형과 비슷하다. Series 객체는 파이썬의 사전형을 인자로 받아야하는 많은 함수에서 사전형을 대체하여 사용할 수 있다. 

In [36]:
'b' in obj2

True

In [37]:
'e' in obj2

False

In [38]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}

In [39]:
obj3 = pd.Series(sdata)

In [40]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [41]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [42]:
obj4 = pd.Series(sdata, index=states)

In [43]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [44]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [45]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [46]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

Series 유용한 기능은 산술 연산에서 색인과 라벨로 자동 정렬하는 것이다. 

In [47]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [48]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [49]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Series 객체와 Series 색인은 모두 name 속성이 있는데 이 속성은 pandas 핵심 기능과 밀접한 관련이 있다. 

In [51]:
obj4.name = 'population'

In [52]:
obj4.index.name = 'state'

In [53]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [54]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [55]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [56]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame
- 색인의 모양이 같은 Series 객체를 담고 있는 파이썬 사전으로 생각하면 편하다. 내부적으로 데이터는 리스트나 사전 또는 1차원 배열을 담고 잇는 다른 컬렉션이 아니라 하나 이상의 2차원 배열에 저장된다. 

In [58]:
data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year' : [2000,2001,2002,2001,2002,2003],
        'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [59]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [60]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [61]:
pd.DataFrame(data, columns=['year','state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [65]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [66]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [67]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [68]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [70]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [71]:
frame2['debt'] = 16.5 

In [73]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [74]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [81]:
frame2['eastern'] = frame2.state =='Ohio'

In [82]:
frame2

year   state  pop  debt  estern  eastern
one    2000    Ohio  1.5   NaN    True     True
two    2001    Ohio  1.7  -1.2    True     True
three  2002    Ohio  3.6   NaN    True     True
four   2001  Nevada  2.4  -1.5   False    False
five   2002  Nevada  2.9  -1.7   False    False
six    2003  Nevada  3.2   NaN   False    False

In [85]:
del frame2['eastern']

In [86]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [96]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 
       'Ohio' : {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [99]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [97]:
frame3 = pd.DataFrame(pop)

In [98]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [100]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [107]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [108]:
pdata = {'Ohio' : frame3['Ohio'][:-1],
         'Nevada' : frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
year              
2001   1.7     2.4
2002   3.6     2.9

In [109]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [110]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [111]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [112]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index

pandas의 index는 표 형식의 데이터에서 각 로우와 컬럼에 대한 이름과 다른 메타데이터를 저장하는 객체다.  
Series나 DataFrame 객체를 생성할 때 사용되는 배열이나 다른 순차적인 이름은 내부적으로 색인으로 변환된다.

In [113]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [114]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [115]:
index[1:]

Index(['b', 'c'], dtype='object')

In [116]:
labels = pd.Index(np.arange(3))

In [117]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [118]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [119]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [120]:
obj2.index is labels

True

In [121]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [122]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [123]:
'Ohio' in frame3.columns

True

In [124]:
2003 in frame3.index

False

In [126]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

### 핵심 기능
- reindex : 새로운 index에 맞도록 객체를 새로 생성한다. 

In [128]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [129]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [130]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [131]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])

In [132]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [133]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [144]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), 
                     index=['a', 'c','d'],
                     columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [137]:
frame2 = frame.reindex(['a','b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [149]:
states = ['Texas', 'Ohio', 'California']
frame.reindex(columns=states)

Texas  Ohio  California
a      1     0           2
c      4     3           5
d      7     6           8

In [146]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [150]:
frame.loc[['c', 'a', 'd'], states]

Texas  Ohio  California
c      4     3           5
a      1     0           2
d      7     6           8

In [151]:
obj = pd.Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])

In [152]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [153]:
new_obj = obj.drop('c')

In [154]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [156]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [158]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio','Colorado','Utah','New York'],
                    columns=['one','two','three','four'])

In [159]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [160]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [161]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [162]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [163]:
data.drop(['two','four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [164]:
obj.drop('c',inplace=True)

In [165]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### index, 선택하기, 거르기

Series의 obj[...]은 NumPy 배열의 index와 유사하게 동작하지만 정수가 아니어도 된다는 점이 다르다. 

In [168]:
obj = pd.Series(np.arange(4.), index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [169]:
obj['b']

1.0

In [170]:
obj[1]

1.0

In [171]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [172]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [173]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [174]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [175]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [176]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [178]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio','Colorado','Utah','New York'],
                    columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [179]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [180]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [181]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [182]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [183]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [184]:
data[data<5]=0

In [185]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### loc과 iloc으로 선택하기

DataFrame의 로우에 대해 라벨로 색인하는 방법으로 특수한 색인 필드인 loc과 iloc을 소개한다.  
이 방법을 이용하면 NumPy와 비슷한 방식에 추가적으로 축의 라벨을 사용하여 DataFrame의 로우와 컬럼을 선택할 수 있다.  
축 이름을 선택할 때는 loc을, 정수 색인으로 선택할 때는 iloc을 사용한다. 

In [187]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [188]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [189]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [190]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [191]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [194]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### 정수 색인

정수 색인으로 pandas 객체를 다루다보면 리스트나 튜플 같은 파이썬 내장 자료구조에서 색인을 다루는 방법과의 차이점 때문에 실수하는 경우가 있다. 

In [201]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

이 경우 pandas는 라벨 색인을 찾는 데 실패하므로 정수 색인으로 값을 찾는다.  
하지만 이를 어떤 경우에도 버그 없이 잘 작동하도록 구현하기란 쉽지 않다.  
라벨 색인이 0,1,2를 포함하는 경우 사용자가 경우 사용자가 라벨 색인으로 선택하려는 것인지 정수 색인으로 선택하려는 것인지 추측하기 쉽지 않다. 

In [214]:
ser2 = pd.Series(np.arange(3), index=['a','b','c'])
ser2

a    0
b    1
c    2
dtype: int32

In [215]:
ser2[-1]

2

In [216]:
ser[:1]

0    0.0
dtype: float64

In [218]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [219]:
ser.iloc[:1]

0    0.0
dtype: float64

### 산술 연산과 데이터 정렬
pandas에서 가장 중요한 기능 중 하나는 다른 색인을 가지고 있는 객체 간의 산술 연산이다.  
객체를 더할 때 짝이 맞지 않는 색인이 있다면 결과에 두 색인이 통합된다.  
데이터베이스를 사용해본 경험이 있다면 색인 라벨에 대한 외부 조인과 유사하게 동작한다고. 
예제를 보자. 

In [220]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],
               index=['a','c','e','f','g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [221]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [222]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [225]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'),
                   index=['Ohio','Texas','Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                   index=['Utah','Ohio','Texas','Oregaon'])

In [226]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [227]:
df2

b     d     e
Utah     0.0   1.0   2.0
Ohio     3.0   4.0   5.0
Texas    6.0   7.0   8.0
Oregaon  9.0  10.0  11.0

In [228]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregaon   NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

'c'와 'e' 컬럼이 양쪽 DataFrame 객체에 존재하지 않으므로 결과에서는 모든 없는 값으로 나타난다.  
로우 역시 마찬가지로 양쪽에 다 존재하지 않는 라벨에 대해서는 없는 값으로 나타난다.   
공통되는 컬럼 라벨이나 로우 라벨이 없는 DataFrame을 더하면 결과에 아무것도 나타나지 않을 것이다. 

In [233]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[3,4]})
df1

A
0  1
1  2

In [234]:
df2

B
0  3
1  4

In [235]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

### 산술 연산 메서드에 채워 넣을 값 지정하기

In [237]:
df1= pd.DataFrame(np.arange(12.).reshape((3,4)),
                  columns=list('abcd'))
df2= pd.DataFrame(np.arange(20.).reshape((4,5)),
                 columns=list('abcde'))
df2.loc[1,'b']=np.nan
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [238]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [239]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [240]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [241]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [242]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### DataFrame과 Series 간의 연산

In [243]:
arr= np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [244]:
arr[0]

array([0., 1., 2., 3.])

In [245]:
arr- arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

### 함수 적용과 매핑

In [247]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                     index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah   -1.863619  0.400305 -0.920241
Ohio    0.709933  0.225949  0.604497
Texas   0.804404  0.612373  0.655053
Oregon -2.183156 -0.478672  0.628320

In [248]:
np.abs(frame)

b         d         e
Utah    1.863619  0.400305  0.920241
Ohio    0.709933  0.225949  0.604497
Texas   0.804404  0.612373  0.655053
Oregon  2.183156  0.478672  0.628320

In [249]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    2.987559
d    1.091045
e    1.575294
dtype: float64

In [250]:
frame.apply(f, axis='columns')

Utah      2.263924
Ohio      0.483984
Texas     0.192031
Oregon    2.811476
dtype: float64

In [251]:
def f(x):
    return pd.Series([x.min(),x.max()], index=['min','max'])
frame.apply(f)

b         d         e
min -2.183156 -0.478672 -0.920241
max  0.804404  0.612373  0.655053

In [252]:
format = lambda x : '%.2f' %x

In [253]:
frame.applymap(format)

b      d      e
Utah    -1.86   0.40  -0.92
Ohio     0.71   0.23   0.60
Texas    0.80   0.61   0.66
Oregon  -2.18  -0.48   0.63

In [254]:
frame['e'].map(format)

Utah      -0.92
Ohio       0.60
Texas      0.66
Oregon     0.63
Name: e, dtype: object